#!/bin/bash

''':'

result1=$(exec python3 --version 2>&1) ; ret1=$?
result2=$(exec python2 --version 2>&1) ; ret2=$?
	

if [ $ret1 -ne 0 ] ; then
	if [ $ret2 -ne 0 ] ; then	
		echo "Error : Not able to execute python3 or python2"
	else
		echo "script run using $result2"
		exec python2 "$0" "$@"
	fi
else
	echo "script run using $result1"
	exec python3 "$0" "$@"
fi
	
exit 0

':'''

import sys
import os.path
import struct

def c_to_hex_b(c2):
    c=[]
    for i in c2:
        if i=='f' or i=='F':
            c.append(15)
        elif i=='e' or i=='E':
            c.append(14)
        elif i=='d' or i=='D':
            c.append(13)
        elif i=='c' or i=='C':
            c.append(12)
        elif i=='b' or i=='B':
            c.append(11)
        elif i=='a' or i=='A':
            c.append(10)
        else:
            c.append(int(i))
    return c[0]*16+c[1]

def wf_hex(hexa,f):
    n=len(hexa)//2
    if len(hexa)%2!=0:
        hexa=hexa+'0'
        n+=1
    for i in range(n):
        f.write(struct.pack("B",c_to_hex_b(hexa[i*2:i*2+2])))

#### get file names ####

all_file=[]
if len(sys.argv)==1:
	while(len(all_file)==0):
		input_file=input("Enter file name(s) : ")
		index=[-1]
		for i in range(len(input_file)):
			if input_file[i]==' ':
				index.append(i)
		index.append(len(input_file))
		all_file=[]
		for i in range(len(index)-1):
			file_i=input_file[index[i]+1:index[i+1]]
			if(len(file_i)!=0):
				all_file.append(file_i)
else:
	for i in range(1,len(sys.argv)):
		all_file.append(sys.argv[i])

print(all_file) #test
	
########################

for i in range(len(all_file)):
	fname=all_file[i]
	if os.path.exists(fname)==False:
		print("file {} not found".format(fname))
	else:
		print("file {} found".format(fname))
		fr=open(fname,"rb")
		contenu=fr.read()
		print(contenu) #test
		fr.close()

		#	
		
		fcreate=fname+".cdt"
		choice='a'
		if os.path.exists(fcreate):
			print("Warning : {} already exist. Do you allow the process to override it?".format(fcreate))
			while(choice!='y' and choice!='n'):
				choice=input("y : delete the file and process compression | n : keep the file and cancel compression (for this file only) : ")
			if choice=='y':
				fw=open(fcreate,"wb")
		else:	
			fw=open(fcreate,"xb")
		if choice!='n':

			#perform compression here using contenu for the file content

			#fw.write(struct.pack("B",0b01000001)) #test
			#fw.write(struct.pack("B",0b01000001)) #test
			#fw.write(struct.pack("B",0x43)) #test
			wf_hex("41ab78fe4541",fw) #test
			#write into file here using hexa code into a char (ex "ab78fe32a4") with wf_hex() function
			fw.close()


