#!/bin/bash

''':'

result1=$(exec python3 --version 2>&1) ; ret1=$?
result2=$(exec python2 --version 2>&1) ; ret2=$?
	

if [ $ret1 -ne 0 ] ; then
	if [ $ret2 -ne 0 ] ; then	
		echo "Error : Not able to execute python3 or python2"
	else
		echo "script run using $result2"
		exec python2 "$0" "$@"
	fi
else
	echo "script run using $result1"
	exec python3 "$0" "$@"
fi
	
exit 0

':'''

import sys

if len(sys.argv)==1:
	input_file=input("Enter file name(s) : ")
	index=[-1]
	for i in range(len(input_file)):
		if input_file[i]==' ':
			index.append(i)
	index.append(len(input_file))
	all_file=[]
	for i in range(len(index)-1):
		file_i=input_file[index[i]+1:index[i+1]]
		if(len(file_i)!=0):
			all_file.append(file_i)
else:
	all_file=[]
	for i in range(1,len(sys.argv)):
		all_file.append(sys.argv[i])

print(all_file) #test
	



